### ISSUE TITLE
Maven Online Repository Update Request

### ISSUE THREAD

**Issue by king-of-knightss** [chiselverify/chiselverify#45]
Hello, I found that in the latest version of chisel verify, you have commented out require in lines 166 and 292 of chiselverify/coverage/CoverReport, but the version you uploaded to the maven online repository has not been updated subsequently.
Could you please update it, thank you~

**Comment by Dobios** [comment]
Hi! Yes of course, this will be done within the day. Sorry for the inconvenience !

**Comment by schoeberl** [comment]
I've updated on Maven. Version 0.3.0 should be visible in a few minutes.
